<a href="https://colab.research.google.com/github/saqlineniam/PyTorch/blob/main/nn_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [52]:
import torch
import torch.nn as nn

In [ ]:
class Model(nn.Module):

  def __init__(self, num_feature):
    super().__init__()
    self.linear1 = nn.Linear(num_feature, 3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)

    return out

In [ ]:

class Model(nn.Module):

  def __init__(self, num_feature):
    super().__init__()
    self.linear1 = nn.Linear(num_feature, 3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)

    return out

In [ ]:
features = torch.rand(10,5)

In [ ]:
model = Model(features.shape[1])

In [ ]:
model(features)

tensor([[0.3948],
        [0.3948],
        [0.3948],
        [0.3948],
        [0.3973],
        [0.3948],
        [0.3948],
        [0.3948],
        [0.3948],
        [0.3948]], grad_fn=<SigmoidBackward0>)

In [ ]:
features

tensor([[0.7748, 0.8448, 0.9826, 0.4951, 0.3538],
        [0.6792, 0.4993, 0.4432, 0.4106, 0.9171],
        [0.6589, 0.6711, 0.1294, 0.3660, 0.7037],
        [0.4771, 0.5061, 0.6923, 0.0826, 0.2134],
        [0.0292, 0.4445, 0.4623, 0.4621, 0.9086],
        [0.8543, 0.6832, 0.6638, 0.5179, 0.9353],
        [0.5742, 0.9651, 0.9309, 0.8492, 0.6609],
        [0.1345, 0.7907, 0.6372, 0.0033, 0.5944],
        [0.8404, 0.7015, 0.5652, 0.1579, 0.1117],
        [0.7539, 0.2630, 0.4491, 0.7905, 0.2093]])

In [ ]:
model.linear2.weight

Parameter containing:
tensor([[ 0.0658, -0.3384, -0.5209]], requires_grad=True)

In [ ]:
model.linear1.bias

Parameter containing:
tensor([-0.0139, -0.2236, -0.1091], requires_grad=True)

In [ ]:
!pip install torchinfo

In [ ]:
from torchinfo import summary

In [ ]:
summary(model, input_size = (10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

Sequential

In [7]:
class Model(nn.Module):

  def __init__(self, num_feature):

    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_feature, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

  def forward(self, features):
    out = self.network(features)

    return out

In [8]:
features = torch.rand(10,5)

In [9]:
model = Model(features.shape[1])

In [10]:
model(features)

tensor([[0.4043],
        [0.4061],
        [0.3998],
        [0.3998],
        [0.4064],
        [0.4118],
        [0.3998],
        [0.4034],
        [0.3998],
        [0.4186]], grad_fn=<SigmoidBackward0>)

In a dataset

In [53]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [54]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [55]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [56]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [57]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [58]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [59]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [63]:
class MySimpleNN(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 1),
        # nn.ReLU(),
        # # nn.Linear(3, 1),
        nn.Sigmoid(),
    )
  def forward(self, features):
    out = self.network(features)
    return out

  def loss_function(self, y_pred, y):
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)
    loss = -(y_train_tensor * torch.log(y_pred) + (1-y_train_tensor) * torch.log(1-y_pred))
    return loss.mean()

In [78]:
class MySimpleNN(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
        # nn.ReLU(),
        # # nn.Linear(3, 1),
    self.sigmoid = nn.Sigmoid()
  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

In [79]:
learning_rate = 0.1
epochs = 25

In [80]:
loss_function = nn.BCELoss()

In [81]:
type(loss_function)

torch.nn.modules.loss.BCELoss

In [82]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)


# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model(X_train_tensor)

  # loss calculate
  loss = loss_function(y_pred, y_train_tensor.reshape(-1,1))

  # zero gradients
  optimizer.zero_grad()

  # backward pass
  loss.backward()

  # parameters update
  optimizer.step()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.7364619970321655
Epoch: 2, Loss: 0.5445861220359802
Epoch: 3, Loss: 0.4435020387172699
Epoch: 4, Loss: 0.3834100365638733
Epoch: 5, Loss: 0.34342503547668457
Epoch: 6, Loss: 0.31458210945129395
Epoch: 7, Loss: 0.29256269335746765
Epoch: 8, Loss: 0.2750469744205475
Epoch: 9, Loss: 0.26067668199539185
Epoch: 10, Loss: 0.24860167503356934
Epoch: 11, Loss: 0.23826093971729279
Epoch: 12, Loss: 0.22926843166351318
Epoch: 13, Loss: 0.22134898602962494
Epoch: 14, Loss: 0.21430067718029022
Epoch: 15, Loss: 0.2079717069864273
Epoch: 16, Loss: 0.20224544405937195
Epoch: 17, Loss: 0.19703052937984467
Epoch: 18, Loss: 0.192254438996315
Epoch: 19, Loss: 0.1878584772348404
Epoch: 20, Loss: 0.18379487097263336
Epoch: 21, Loss: 0.18002387881278992
Epoch: 22, Loss: 0.1765124350786209
Epoch: 23, Loss: 0.1732325255870819
Epoch: 24, Loss: 0.17016038298606873
Epoch: 25, Loss: 0.1672755628824234


In [83]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')


Accuracy: 0.5646352767944336
