<a href="https://colab.research.google.com/github/saqlineniam/PyTorch/blob/main/pytorch_training_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [5]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

Train-Test Split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [7]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

Converting to tensor

In [9]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [10]:
X_train_tensor.shape

torch.Size([455, 30])

In [11]:
X_train_tensor

tensor([[-1.3843,  0.5461, -1.3765,  ..., -1.1690, -0.0142, -0.0055],
        [ 1.2929,  1.3341,  1.3785,  ...,  1.1149,  0.9483,  0.8531],
        [-0.6457, -1.0114, -0.6315,  ..., -1.0143,  0.4099, -0.4203],
        ...,
        [ 0.0218,  0.6501,  0.1793,  ...,  1.0171, -0.0613,  1.7466],
        [-0.4948, -0.4683, -0.4955,  ..., -0.1194,  0.2601, -0.3791],
        [-0.8169, -0.4083, -0.8318,  ..., -0.4038,  0.1558, -0.3303]],
       dtype=torch.float64)

Defining the model

In [15]:
X_train_tensor.shape[1],1

(30, 1)

In [32]:
class MySimpleNN():

  def __init__(self, X):

    self.weights = torch.rand(X.shape[1],1, dtype = torch.float64, requires_grad = True)
    self.bias = torch.zeros(1, dtype = torch.float64, requires_grad = True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    return torch.sigmoid(z)

  def loss_function(self, y_pred, y):
    epsilon = 1e-7

    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)
    loss = -y * torch.log(y_pred) - (1-y) * torch.log(1-y_pred)
    return torch.mean(loss)

Important Parameter

In [36]:
learning_rate = 0.1
epochs = 100

Training Pipeline

In [37]:
#create model
model = MySimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):

  # FORWARD PASS
  y_pred = model.forward(X_train_tensor)
  # print(y_pred)

  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)
  # print(loss)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero grad
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch+1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.6677697728538163
Epoch: 2, Loss: 3.541584619876035
Epoch: 3, Loss: 3.413393893581332
Epoch: 4, Loss: 3.279214168063405
Epoch: 5, Loss: 3.141568740743864
Epoch: 6, Loss: 3.0000492492395567
Epoch: 7, Loss: 2.847130351660573
Epoch: 8, Loss: 2.6893249416072975
Epoch: 9, Loss: 2.5224781484990566
Epoch: 10, Loss: 2.350909208729843
Epoch: 11, Loss: 2.178710689316459
Epoch: 12, Loss: 2.0066686253457684
Epoch: 13, Loss: 1.8391446092974837
Epoch: 14, Loss: 1.677151798117551
Epoch: 15, Loss: 1.5253797583739859
Epoch: 16, Loss: 1.3859098250196193
Epoch: 17, Loss: 1.2589707270366015
Epoch: 18, Loss: 1.141906532125098
Epoch: 19, Loss: 1.0435535319971254
Epoch: 20, Loss: 0.9642695598089349
Epoch: 21, Loss: 0.903094358781545
Epoch: 22, Loss: 0.8578542439139145
Epoch: 23, Loss: 0.8255343915682147
Epoch: 24, Loss: 0.8028641250446635
Epoch: 25, Loss: 0.7868978246371837
Epoch: 26, Loss: 0.7753470973841691
Epoch: 27, Loss: 0.7666207107667371
Epoch: 28, Loss: 0.7596924406030862
Epoch: 29, 

In [38]:
model.weights

tensor([[ 0.2191],
        [ 0.2175],
        [ 0.1544],
        [ 0.0158],
        [-0.1662],
        [ 0.3746],
        [-0.3056],
        [ 0.0985],
        [-0.0423],
        [ 0.0633],
        [-0.4727],
        [-0.0462],
        [-0.1034],
        [ 0.4372],
        [ 0.0952],
        [-0.1609],
        [ 0.3120],
        [-0.1133],
        [ 0.1421],
        [-0.0864],
        [ 0.2207],
        [-0.1810],
        [-0.4879],
        [ 0.1471],
        [ 0.2587],
        [-0.2283],
        [ 0.2245],
        [-0.2801],
        [-0.0657],
        [ 0.0633]], dtype=torch.float64, requires_grad=True)

In [39]:
model.bias

tensor([-0.4579], dtype=torch.float64, requires_grad=True)

Evaluation

In [43]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy}')


Accuracy: 0.6061865091323853
