<a href="https://colab.research.google.com/github/saqlineniam/PyTorch/blob/main/tensors_in_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)

2.8.0+cu126


In [2]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"using GPU: {torch.cuda.get_device_name(0)}")

else:
  print("GPU is not available")

GPU is available
using GPU: Tesla T4


Creating Tensor

In [3]:
# using empty

a = torch.empty(2,3)

In [4]:
# check type
type(a)

torch.Tensor

In [9]:
# using zeros

torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [11]:
# using ones

torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [12]:
# torch rand

torch.rand(2,3)

tensor([[0.0766, 0.2580, 0.9079],
        [0.8540, 0.9430, 0.0945]])

In [ ]:
# use of seed

torch.rand(2,3)

In [13]:
# manual seed

torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [16]:
# using tensor

torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [18]:
# other ways

#arange
print("using arange ->", torch.arange(0,10))

# using linspace
print("using linspace - >", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))


#using full
print("using full ->", torch.full((3,3), 5))

using arange -> tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
using linspace - > tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


Tensor Shapes

In [5]:
x = torch.tensor([[1,3,5], [6,8,10]])

In [6]:
x.shape

torch.Size([2, 3])

In [7]:
torch.empty_like(x)

tensor([[3904678266855766562, 7161628500580249958, 7362648937812208949],
        [3761180106852349493, 7161113949703911013, 8243121639892462626]])

In [8]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [9]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [10]:
torch.rand_like(x)

NotImplementedError: "check_uniform_bounds" not implemented for 'Long'

Tensor Data Types

In [11]:
x

tensor([[ 1,  3,  5],
        [ 6,  8, 10]])

In [12]:
x.dtype

torch.int64

In [13]:
# assign data type

torch.tensor([1.0,2.0,3.0], dtype = torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [14]:
torch.tensor([1,2,3,4], dtype = torch.float32)

tensor([1., 2., 3., 4.])

In [15]:
# using to()
x = x.to(torch.float32)

Mathematical Operations

1. Scaler operation

In [16]:
x = torch.rand(2,3)
x

tensor([[0.2824, 0.7067, 0.1256],
        [0.9934, 0.6103, 0.2341]])

In [17]:
# addition
x+2

#substraction
x-2

#multiplication
x*2

#division
x/2

#power
x**2

#mod
x%2



tensor([[0.2824, 0.7067, 0.1256],
        [0.9934, 0.6103, 0.2341]])

2. Element wise operation

In [18]:
a = torch.rand(2,3)
b = torch.rand(2,3)

In [19]:
print(a)
print(b)

tensor([[0.3531, 0.7117, 0.2325],
        [0.0979, 0.7902, 0.7538]])
tensor([[0.6502, 0.3427, 0.7540],
        [0.6932, 0.2781, 0.9665]])


In [20]:
a+b

tensor([[1.0033, 1.0544, 0.9865],
        [0.7911, 1.0682, 1.7203]])

In [21]:
a-b

tensor([[-0.2970,  0.3690, -0.5215],
        [-0.5953,  0.5121, -0.2127]])

In [22]:
a*b

tensor([[0.2296, 0.2439, 0.1753],
        [0.0679, 0.2197, 0.7286]])

In [30]:
c = torch.tensor([1.2,2.9,3.7,-4])

In [31]:
torch.abs(c)

tensor([1.2000, 2.9000, 3.7000, 4.0000])

In [32]:
torch.round(c)

tensor([ 1.,  3.,  4., -4.])

In [35]:
torch.ceil(c)

tensor([ 2.,  3.,  4., -4.])

In [36]:
torch.clamp(c,min = 2, max = 4)

tensor([2.0000, 2.9000, 3.7000, 2.0000])

reductionn operation

In [45]:
e = torch.randint(size = (2,3), low = 0, high = 10, dtype = torch.float32)
e

tensor([[5., 0., 5.],
        [1., 9., 8.]])

In [46]:
torch.sum(e)

tensor(28.)

In [50]:
torch.sum(e, dim=0)

tensor([ 6.,  9., 13.])

In [51]:
torch.mean(e, dim=0)

tensor([3.0000, 4.5000, 6.5000])

In [52]:
torch.std(e)

tensor(3.6148)

In [53]:
torch.var(e)

tensor(13.0667)

In [54]:
torch.argmax(e)

tensor(4)

In [55]:
torch.argmin(e)

tensor(1)

In [56]:
f = torch.randint(size = (2,3), low = 0, high = 10, dtype = torch.float32)
g = torch.randint(size = (3,4), low = 10, high = 20, dtype = torch.float32)

In [57]:
torch.matmul(f,g)

tensor([[253., 207., 235., 250.],
        [190., 193., 166., 176.]])